// NOTE: These are all constants, but everything is going to throw a compiler warning
// if I actually use const (since it is discarded), so I'm leaving it off for now.

// Misc Shared Constants
#define SLIDE_SPEED 0.4
#define FADE_SPEED 0.4

// Score Modes
#define PM_SCOREMODE_FREEPLAY 0
#define PM_SCOREMODE_TIMED2MINUTE 1

// User Defaults Keys
#define PM_USERDEFAULT_PLAYSOUND @"PLAY_SOUNDS"
#define PM_USERDEFAULT_GRAVITYLOCK @"GRAVITY_LOCK"
#define PM_USERDEFAULT_RESOURCEBUNDLEVERSION @"RESOURCE_BUNDLE_VERSION"

// Analytics Keys
#define PM_ANALYTICS_VIEW_HIGHSCORE @"VIEW_HIGHSCORE"
#define PM_ANALYTICS_CALCULATED_SCORE @"CALCULATED_SCORE"
#define PM_ANALYTICS_DETAILED_SCORE @"DETAILED_SCORE"
#define PM_ANALYTICS_STARTED_TIMED_GAME @"STARTED_TIMED_GAME"
#define PM_ANALYTICS_STARTED_FREEPLAY_GAME @"STARTED_FREEPLAY_GAME"
#define PM_ANALYTICS_EXITED_GAME_EARLY @"EXITED_GAME_EARLY"
#define PM_ANALYTICS_GAMES_PLAYED_SESSION @"GAMES_PLAYED_SESSION"
#define PM_ANALYTICS_GAMES_STARTED_SESSION @"GAMES_STARTED_SESSION"
#define PM_ANALYTICS_STORE_OPENED @"STORE_OPENED"

// Sound Effects
#define PM_SOUND_BUTTONCLICK 0
#define PM_SOUND_SCOREDING 1
#define PM_SOUND_HAMMERCLICK1 2
#define PM_SOUND_HAMMERCLICK2 3
#define PM_SOUND_HAMMERCLICK3 4
#define PM_SOUND_BALLONPLASTIC1 5
#define PM_SOUND_MULTIPLIER_X2 6
#define PM_SOUND_MULTIPLIER_X3 7
#define PM_SOUND_MULTIPLIER_X4 8
#define PM_SOUND_MULTIPLIER_X5 9
#define PM_SOUND_CLOCKTICK 10
#define PM_SOUND_VICTORY 11


// Sound Channel Groups
#define PM_CHANNELGROUP_SOUNDEFFECTS 0

// Achievements
#define PM_OPENFEINT_ACHIEVEMENT_FIRSTSCORE @"192083"
#define PM_OPENFEINT_ACHIEVEMENT_TIMEDGAMECOMPLETE @"206523"
#define PM_OPENFEINT_ACHIEVEMENT_MULTIPLIER2X @"206533"
#define PM_OPENFEINT_ACHIEVEMENT_MULTIPLIER3X @"206543"
#define PM_OPENFEINT_ACHIEVEMENT_MULTIPLIER4X @"206553"
#define PM_OPENFEINT_ACHIEVEMENT_MULTIPLIER5X @"206563"
#define PM_OPENFEINT_ACHIEVEMENT_ALLBALLSINDIFFERENTCUPS @"206573"
#define PM_OPENFEINT_ACHIEVEMENT_ONEMILLIONPOINTS @"206583"

